Repository onclick-academy/onclick-client, pull requests merged in 2024-03, with the labels that each got.

#17 feat[frontend]: Implement instructor application view
  src/app/applyinstructor/page.tsx
  src/components/Form/ApplyInstructor.tsx
  src/styles/applyInstructor.css
Labels: enhancement, next14, frontend, view

#20 Feat/frontend/19/seature implement intro section
  dummy.tsx
  package.json
  src/SVGS/sv1.svg
  src/SVGS/sv2.svg
  src/SVGS/sv3.svg
  src/SVGS/sv4.svg
  src/SVGS/sv5.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Cursor/Cursor.tsx
  src/components/Header/AnimatedHeader.module.scss
  src/components/Header/AnimatedHeader.tsx
  src/components/Header/Header.tsx
  src/components/Header/Headtrial.tsx
  src/components/Header/SvgAnimate.tsx
  src/components/Header/Svgs.tsx
  src/components/Header/ani.tsx
  src/components/Main/Intro.module.css
  src/components/Main/Intro.tsx
  src/components/Main/IntroVideo.tsx
  src/components/Main/Main.tsx
  src/components/Main/ReviewCounter.module.css
  src/components/Main/Reviewcounter.tsx
  src/components/Nav/Nav.tsx
  src/components/Notification/Notifications.tsx
  src/components/Pops&Drops/SideList.tsx
  src/components/Pops&Drops/TabPanel.tsx
  src/components/Swipe/Swipe.module.scss
  src/components/Swipe/Swipe.tsx
  src/components/Swiper/MySwiper.tsx
  src/components/TextReaveal/A4Layout.tsx
  src/components/TextReaveal/AnimText.tsx
  src/components/TextReaveal/CursorBlinker.tsx
  src/components/TextReaveal/RedoAnimText.tsx
  src/img/Cloud.png
  src/img/Review.svg
  src/img/Sun.png
  src/img/Train.png
  src/img/ceo.png
  src/img/counterBack.jpeg
  src/img/intro1.png
  src/img/intro2.png
  src/img/intro3.jpeg
  src/img/intro4.jpeg
  src/img/logo.png
  src/img/logo2.png
  src/img/logo3.png
  yarn.lock
Labels: frontend

#27 feat-frontend-23-implement_notification_full_functionality
  .gitignore
  Login.tsx
  dummy.tsx
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/app/registeration/page.tsx
  src/components/Cursor/Cursor.tsx
  src/components/Form/Login.tsx
  src/components/Form/Register.tsx
  src/components/Nav/Nav.tsx
  src/components/Notification/NotifiacationItem.tsx
  src/components/Notification/NotificationIcons.tsx
  src/components/Notification/index.tsx
  src/components/Notification/notification.scss
  src/components/Notification/utiliy.tsx
  src/components/Swipe/Swipe.tsx
  src/components/Swiper/MySwiper.tsx
  src/firebase/index.tsx
  src/utilities/device.ts
  src/utilities/fetcher.ts
  src/utilities/getAuthUser.ts
  src/utilities/notification/sendNotification.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, next14, frontend, landing-page
